HomePageTitle: Hello
NotAnAdmin: You must be an administrator to access this page.

WelcomeHomepage: Welcome to the homepage
SeeArchive: See the archive

NoEntries: There are no entries in the blog
Login: Login
LoginToPost: Admins can login to post
NewEntry: Post to blog
NewEntryTitle: Title
NewEntryContent: Content

PleaseCorrectEntry: Your submitted entry had some errors, please correct and try again.
EntryCreated title@Text: Your new blog post, #{title}, has been created

EntryTitle title@Text: Blog post: #{title}
CommentsHeading: Comments
NoComments: There are no comments
AddCommentHeading: Add a Comment
LoginToComment: You must be logged in to comment
AddCommentButton: Add comment

CommentName: Your display name
CommentText: Comment
CommentAdded: Your comment has been added
PleaseCorrectComment: Your submitted comment had some errors, please correct and try again.

HomepageTitle: Yesod Blog Demo
BlogArchiveTitle: Blog Archive

FundTitle personName@Text: Slush Fund with #{personName}
FundHeaderTitle: Slush Fund with 
AllFundsTitle: Your SlushFunds
NoFunds: You don't have any funds. Please use the form below to create one or more.

PhoneNumTitle: Phone Number
EmailAddressTitle: E-mail Address
NewUserSearchTitle: See if someone already has a slushfund with you
NewUserSearchExplanation: Other users may already be tracking expenses with you. Please search by email address and phone number to see if this is the case. If so, you can link to these SlushFunds by either receiving an e-mail with a verification link or an SMS message to your phone.
SearchButtonTitle: Search

FirstName: First Name
LastName: Last Name
NickName: Nickname
FindPerson: Find a person to start a fund with
FindPersonLink: Find a person to start a fund with
FindButtonTitle: Find
CreateFundWithHeader: Create New Fund
CreateFundWithMsg: Select a user below to create a SlushFund with. If the person you are looking for does not appear to be a current user, use the form at the bottom to create fund. Please e-mail that person and tell them they can log in and use the joint SlushFund by logging in with the e-mail you specify.
FundWithPersonButtonTitle personName@Text: Fund with #{personName}
CannotCreateFundWSelf: You shouldn't be able to create a fund linking to yourself. Please report bug with steps to reproduct it to scaledsoftware /at/ google /dot/ com

UpdateButtonTitle: Update
PersonInfo personName@Text: Update Information for Person: #{personName}
PersonUpdated personName@Text: Information for #{personName} was updated.
PleaseCorrectPersonEntry: The entered information could not be processed. Please correct it and resubmit.
AKA: also known as
Notes: Notes
WhereDidTransactionOccur: Name of Merchant

Date: Date
Time: Time
Amount: Amount
SplitCheck: Split Check?
SelectPayer: Select who paid:
PleaseCorrectFundEntry: Please correct fund entry. All fields are required.
SubmitFundEntry: Submit

EvenSteven: The two of your are essentially even.
IOwe them@Text: I need to buy the next round, I owe #{them}
TheyOwe them@Text: #{them} should buy soon, they owe
