HomePageTitle: Hello
NotAnAdmin: You must be an administrator to access this page.

WelcomeHomepage: Welcome to the homepage
SeeArchive: See the archive

NoEntries: There are no entries in the blog
LoginToPost: Admins can login to post
NewEntry: Post to blog
NewEntryTitle: Title
NewEntryContent: Content

PleaseCorrectEntry: Your submitted entry had some errors, please correct and try again.
EntryCreated title@Text: Your new blog post, #{title}, has been created

EntryTitle title@Text: Blog post: #{title}
CommentsHeading: Comments
NoComments: There are no comments
AddCommentHeading: Add a Comment
LoginToComment: You must be logged in to comment
AddCommentButton: Add comment

CommentName: Your display name
CommentText: Comment
CommentAdded: Your comment has been added
PleaseCorrectComment: Your submitted comment had some errors, please correct and try again.

HomepageTitle: Yesod Blog Demo
BlogArchiveTitle: Blog Archive

FundTitle personName@Text: Slush Fund with #{personName}
AllFundsTitle: List of all Slush Funds
NoFunds: You don't have any funds. Please use the form below to create one or more.

PhoneNumTitle: Phone Number
EmailAddressTitle: E-mail Address
NewUserSearchTitle: See if someone already has a slushfund with you
NewUserSearchExplanation: Other users may already be tracking expenses with you. Please search by email address and phone number to see if this is the case. If so, you can link to these SlushFunds by either receiving an e-mail with a verification link or an SMS message to your phone.
SearchButtonTitle: Search

FirstName: First Name
LastName: Last Name
NickName: Nickname

UpdateButtonTitle: Update
PersonInfo personName@Text: Update Information for Person: #{personName}
PersonUpdated personName@Text: Information for #{personName} was udpated.
PleaseCorrectPersonEntry: The entered information could not be processed. Please correct it and resubmit.
