Default: &defaults
  user: slushfund
  password: slushfund
  host: 192.168.1.90
  port: 5432
  database: slushfund
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: slushfund_test
  <<: *defaults

Staging:
  database: slushfund_staging
  poolsize: 100
  <<: *defaults

Production:
  database: slushfund_production
  poolsize: 100
  <<: *defaults
