Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://192.168.1.72:3000"
  copyright: Copyright 2013  
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.slushfund.com"
  <<: *defaults
